---
version: '3'
services:
  db:
    image: ${REGISTRY_URL}/ventilar-db:latest
    container_name: ventilar-db
    # ports:
    #   - 5434:5432
  api:
    image: ${REGISTRY_URL}/ventilar-api:latest
    container_name: ventilar-api
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      ACCESS_TOKEN_DURATION: ${ACCESS_TOKEN_DURATION}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_DURATION: ${REFRESH_TOKEN_DURATION}
    # ports: #host : container
    #   - 3002:3002
  app:
    image: ${REGISTRY_URL}/ventilar-app:latest
    container_name: ventilar-app
    environment:
      API_URL: ${API_URL}
    # ports: #host : container
    #   - 8088:80
